### ISSUE TITLE
运行后提示

### ISSUE THREAD

**Issue by raclen** [Lucifier129/react-imvc-template#7]
npm start后
```

Warning: Accessing PropTypes via the main React package is deprecated, and will
be removed in  React v16.0. Use the latest available v15.* prop-types package fr
om npm instead. For info on usage, compatibility, migration and more, see https:
//fb.me/prop-types-docs
Listening on port 3000
Hash: 6ad071e236153c911434
Version: webpack 1.13.2
Time: 11718ms
        Asset       Size  Chunks             Chunk Names
     index.js     133 kB       0  [emitted]  index
    vendor.js    1.39 MB       1  [emitted]  vendor
 index.js.map     142 kB       0  [emitted]  index
vendor.js.map    1.89 MB       1  [emitted]  vendor
../stats.json  111 bytes          [emitted]
webpack: Compiled successfully.
GET / 404 61.800 ms - -
GET / 404 49.574 ms - -
GET / 404 51.867 ms - -
GET / 404 45.028 ms - -
GET / 404 64.070 ms - -
GET / 404 55.224 ms - -
GET / 404 45.507 ms - -
GET / 404 52.162 ms - -
GET / 404 53.206 ms - -
GET / 404 48.400 ms - -
GET / 404 50.567 ms - -
GET / 404 47.376 ms - -
GET / 404 39.492 ms - -
GET / 404 37.540 ms - -
GET / 404 48.766 ms - -
GET /favicon.ico 404 34.507 ms - -
```

访问http://localhost:3000/
```
Did not match any route with path:/
Error: Did not match any route with path:/
at fetchController (D:\raclen\react-imvc-template\node_modules\create-app\lib\server\createApp.js:117:25)
at Object.render (D:\raclen\react-imvc-template\node_modules\create-app\lib\server\createApp.js:71:37)
at _callee$ (D:/raclen/react-imvc-template/react-imvc/page/index.js:113:19)
at tryCatch (D:\raclen\react-imvc-template\node_modules\regenerator-runtime\runtime.js:65:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (D:\raclen\react-imvc-template\node_modules\regenerator-runtime\runtime.js:303:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (D:\raclen\react-imvc-template\node_modules\regenerator-runtime\runtime.js:117:21)
at step (D:\raclen\react-imvc-template\react-imvc\page\index.js:31:191)
at D:\raclen\react-imvc-template\react-imvc\page\index.js:31:437
at D:\raclen\react-imvc-template\react-imvc\page\index.js:31:99
at D:/raclen/react-imvc-template/react-imvc/page/index.js:90:1
```
咋办

**Comment by Lucifier129** [comment]
在 package.json 里的 config.vd 配置了路由的 basename，要加上它才可以。

```shell
http://localhost:3000/test
```

目前 react-imvc 还在整理和补充文档。
